<?php


class Expertrecsearch_Public {


	private $plugin_name;

	private $version;

	public function __construct( $plugin_name, $version ) {
		do_action( 'er/debug', 'public construct' );
		$this->plugin_name = $plugin_name;
		$this->version     = $version;
	}


	public function ci_search_form( $form ) {
		do_action( 'er/debug', 'In ci search form' );
		return <<<HEREDOC
	     <ci-search></ci-search>
HEREDOC;
	}

	public function expertrec_js_snippet() {
		do_action( 'er/debug', 'In expertrec js snippet' );
		$site_id         = get_option( 'expertrec_options' )['site_id'];
		$default_site_id = '58c9e0e4-78e5-11ea-baf0-0242ac130002';
		$safe_id         = isset( $site_id ) ? $site_id : $default_site_id;

		echo '<!-- Generated by ExpertRec plugin -->' . PHP_EOL;
		echo '<script>' . PHP_EOL;
		echo '    (function() {' . PHP_EOL;
		echo '        var ci_search = document.createElement(\'script\');' . PHP_EOL;
		echo '        ci_search.type = \'text/javascript\';' . PHP_EOL;
		echo '        ci_search.async = true;' . PHP_EOL;
		echo '        ci_search.src = \'' . esc_url( "https://cse.expertrec.com/api/js/ci_common.js?id=$safe_id" ) . '\';' . PHP_EOL;
		echo '        var s = document.getElementsByTagName(\'script\')[0];' . PHP_EOL;
		echo '        s.parentNode.insertBefore(ci_search, s);' . PHP_EOL;
		echo '    })();' . PHP_EOL;
		echo '</script>' . PHP_EOL;
		echo '<!-- End of content generated by ExpertRec plugin -->' . PHP_EOL;
	}
}
